# Generated by Django 5.1.4 on 2025-01-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human_Player_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('match_number', models.IntegerField(default=0)),
                ('event', models.CharField(default='testing', max_length=16)),
                ('human_player_comment', models.CharField(default='None', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Match_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('event', models.CharField(default='testing', max_length=16)),
                ('match_number', models.IntegerField()),
                ('quantifier', models.CharField(max_length=10)),
                ('auto_leave', models.IntegerField()),
                ('auto_net', models.IntegerField()),
                ('auto_processor', models.IntegerField()),
                ('auto_removed', models.IntegerField()),
                ('auto_L1', models.IntegerField()),
                ('auto_L2', models.IntegerField()),
                ('auto_L3', models.IntegerField()),
                ('auto_L4', models.IntegerField()),
                ('telenet', models.IntegerField()),
                ('teleProcessor', models.IntegerField()),
                ('teleRemoved', models.IntegerField()),
                ('teleL1', models.IntegerField()),
                ('teleL2', models.IntegerField()),
                ('teleL3', models.IntegerField()),
                ('teleL4', models.IntegerField()),
                ('climb', models.IntegerField()),
                ('driver_ranking', models.IntegerField()),
                ('defense_ranking', models.IntegerField()),
                ('comment', models.CharField(max_length=256)),
                ('is_broken', models.IntegerField(default=0)),
                ('is_disabled', models.IntegerField(default=0)),
                ('is_tipped', models.IntegerField(default=0)),
                ('scout_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('event', models.CharField(default='testing', max_length=16)),
                ('robot_picture', models.URLField(blank=True, null=True)),
                ('drivetrain', models.CharField(blank=True, max_length=32, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('intake_design', models.CharField(blank=True, max_length=50, null=True)),
                ('intake_locations', models.CharField(blank=True, max_length=50, null=True)),
                ('scoring_locations', models.CharField(blank=True, max_length=50, null=True)),
                ('auto_positions', models.CharField(blank=True, max_length=50, null=True)),
                ('auto_leave', models.CharField(blank=True, max_length=3, null=True)),
                ('auto_total_notes', models.IntegerField(blank=True, null=True)),
                ('auto_amp_notes', models.IntegerField(blank=True, null=True)),
                ('additional_info', models.CharField(blank=True, max_length=512, null=True)),
                ('pit_scout_status', models.BooleanField(default=False)),
            ],
        ),
    ]
