# Generated by Django 5.1.4 on 2025-02-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human_Player_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('match_number', models.IntegerField(default=0)),
                ('event', models.CharField(default='testing', max_length=16)),
                ('human_player_comment', models.CharField(default='None', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Match_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('event', models.CharField(default='testing', max_length=16)),
                ('match_number', models.IntegerField()),
                ('quantifier', models.CharField(max_length=10)),
                ('start_pos', models.IntegerField(default=0)),
                ('auto_leave', models.IntegerField()),
                ('auto_L1', models.IntegerField()),
                ('auto_L2', models.IntegerField()),
                ('auto_L3', models.IntegerField()),
                ('auto_L4', models.IntegerField()),
                ('auto_net', models.IntegerField()),
                ('auto_processor', models.IntegerField()),
                ('auto_removed', models.IntegerField()),
                ('teleL1', models.IntegerField()),
                ('teleL2', models.IntegerField()),
                ('teleL3', models.IntegerField()),
                ('teleL4', models.IntegerField()),
                ('telenet', models.IntegerField()),
                ('teleProcessor', models.IntegerField()),
                ('teleRemoved', models.IntegerField()),
                ('climb', models.IntegerField()),
                ('driver_ranking', models.IntegerField()),
                ('defense_ranking', models.IntegerField()),
                ('comment', models.CharField(max_length=256)),
                ('is_broken', models.IntegerField(default=0)),
                ('is_disabled', models.IntegerField(default=0)),
                ('is_tipped', models.IntegerField(default=0)),
                ('auto_path', models.JSONField(default=list)),
                ('scout_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.IntegerField()),
                ('event', models.CharField(max_length=10)),
                ('drivetrain', models.CharField(max_length=50)),
                ('weight', models.IntegerField(null=True)),
                ('length', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('intake_design', models.CharField(max_length=50)),
                ('intake_locations', models.CharField(max_length=100)),
                ('scoring_locations', models.CharField(max_length=100)),
                ('cage_positions', models.CharField(max_length=100)),
                ('under_shallow', models.CharField(max_length=10)),
                ('algae_picker', models.CharField(max_length=10)),
                ('auto_positions', models.CharField(max_length=100)),
                ('auto_leave', models.CharField(max_length=10)),
                ('auto_algae_max', models.IntegerField(null=True)),
                ('auto_coral_max', models.IntegerField(null=True)),
                ('robot_picture', models.URLField(null=True)),
                ('additional_info', models.TextField(null=True)),
                ('pit_scout_status', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('team_number', 'event')},
            },
        ),
    ]
