# Generated by Django 5.1.4 on 2025-02-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_match_data',
            name='missed',
            field=models.IntegerField(default=0),
        ),
    ]
