# Generated by Django 4.2.9 on 2024-03-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_match_data',
            name='is_broken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team_match_data',
            name='is_disabled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team_match_data',
            name='is_tipped',
            field=models.IntegerField(default=0),
        ),
    ]
