# Generated by Django 5.1.4 on 2025-01-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='auto_amp_notes',
            new_name='auto_coral_notes',
        ),
        migrations.RemoveField(
            model_name='team_match_data',
            name='name',
        ),
        migrations.AddField(
            model_name='teams',
            name='cage_positions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='removeable',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='under_shallow_coral',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
