# Generated by Django 5.1.4 on 2025-02-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_match_data_missed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_match_data',
            old_name='missed',
            new_name='missed_auto',
        ),
        migrations.AddField(
            model_name='team_match_data',
            name='missed_teleop',
            field=models.IntegerField(default=0),
        ),
    ]
