# Generated by Django 4.2.9 on 2024-04-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_match_data_is_broken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_match_data',
            name='teleop_pass',
            field=models.IntegerField(default=0),
        ),
    ]
