# Generated by Django 5.1.4 on 2025-02-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_add_start_pos_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_match_data',
            name='auth_path',
            field=models.JSONField(default=list),
        ),
    ]
