# Generated by Django 5.1.4 on 2025-02-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_match_data_auth_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team_match_data',
            old_name='auth_path',
            new_name='auto_path',
        ),
    ]
