# Generated by Django 5.1.4 on 2025-02-22 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_rename_missed_team_match_data_missed_auto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_match_data',
            name='missed_teleop',
        ),
    ]
