# Generated by Django 5.1.4 on 2025-10-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_match_data_missed_teleop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_match_data',
            name='quantifier',
            field=models.CharField(choices=[('Quals', 'Qualifications'), ('Playoff', 'Play Off'), ('Prac', 'Practice')], default='Prac', max_length=10),
        ),
    ]
