# Generated by Django 5.1.4 on 2025-10-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_match_data_quantifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_match_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='quantifier',
            field=models.CharField(choices=[('Quals', 'Qualifications'), ('Playoff', 'Play Off'), ('Prac', 'Practice')], default='Quals', max_length=10),
        ),
    ]
