# Generated by Django 5.1.4 on 2025-10-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_team_match_data_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team_match_data',
            unique_together={('team_number', 'event', 'match_number')},
        ),
    ]
