# Generated by Django 5.1.4 on 2025-10-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_team_match_data_quantifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_match_data',
            name='auto_L1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='auto_L2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='auto_L3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='auto_L4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='auto_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='auto_net',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='auto_processor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='auto_removed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='climb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='defense_ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='driver_ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='teleL1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='teleL2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='teleL3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='teleL4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='teleProcessor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='teleRemoved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team_match_data',
            name='telenet',
            field=models.IntegerField(default=0),
        ),
    ]
