# Generated by Django 5.1.4 on 2026-01-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_add_anchor_subjective_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='logo_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
