# Generated by Django 5.1.4 on 2026-03-21 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_add_logo_url'),
        ('teams', '0008_alter_team_match_data_unique_together'),
    ]

    operations = [
    ]
