# Generated by Django 5.1.15 on 2026-05-02 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_merge_20260320_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_match_data',
            name='is_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
