# Generated by Django 4.2.9 on 2024-04-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE strategy_picklist_data ALTER COLUMN dn_pick TYPE jsonb USING to_jsonb(dn_pick);"
            ),
            reverse_sql=(
                "ALTER TABLE strategy_picklist_data ALTER COLUMN dn_pick TYPE integer[] USING array(SELECT jsonb_array_elements_text(dn_pick)::integer);"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE strategy_picklist_data ALTER COLUMN first_pick TYPE jsonb USING to_jsonb(first_pick);"
            ),
            reverse_sql=(
                "ALTER TABLE strategy_picklist_data ALTER COLUMN first_pick TYPE integer[] USING array(SELECT jsonb_array_elements_text(first_pick)::integer);"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE strategy_picklist_data ALTER COLUMN second_pick TYPE jsonb USING to_jsonb(second_pick);"
            ),
            reverse_sql=(
                "ALTER TABLE strategy_picklist_data ALTER COLUMN second_pick TYPE integer[] USING array(SELECT jsonb_array_elements_text(second_pick)::integer);"
            ),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE strategy_picklist_data ALTER COLUMN third_pick TYPE jsonb USING to_jsonb(third_pick);"
            ),
            reverse_sql=(
                "ALTER TABLE strategy_picklist_data ALTER COLUMN third_pick TYPE integer[] USING array(SELECT jsonb_array_elements_text(third_pick)::integer);"
            ),
        ),
    ]
