# Generated by Django 4.2.9 on 2024-04-05 23:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist_data',
            name='dn_pick',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), size=None),
        ),
        migrations.AlterField(
            model_name='picklist_data',
            name='first_pick',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), size=None),
        ),
        migrations.AlterField(
            model_name='picklist_data',
            name='second_pick',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), size=None),
        ),
        migrations.AlterField(
            model_name='picklist_data',
            name='third_pick',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=list), size=None),
        ),
    ]
