# Generated by Django 5.1.4 on 2026-03-21 02:20

from django.db import migrations


class Migration(migrations.Migration):
    """
    0003 already converted these columns via RunSQL + to_jsonb().
    This migration ensures they are jsonb regardless of whether 0003
    ran its SQL (it may have been fake-applied on some databases).
    Using to_jsonb() works safely from both integer[] and jsonb.
    """

    dependencies = [
        ('strategy', '0003_picklist_data_no_pick_alter_picklist_data_dn_pick_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE strategy_picklist_data ALTER COLUMN dn_pick TYPE jsonb USING to_jsonb(dn_pick);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE strategy_picklist_data ALTER COLUMN first_pick TYPE jsonb USING to_jsonb(first_pick);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE strategy_picklist_data ALTER COLUMN second_pick TYPE jsonb USING to_jsonb(second_pick);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE strategy_picklist_data ALTER COLUMN third_pick TYPE jsonb USING to_jsonb(third_pick);",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
