# Generated by Django 5.1.4 on 2026-03-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_alter_picklist_data_dn_pick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist_data',
            name='dn_pick',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='picklist_data',
            name='first_pick',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='picklist_data',
            name='second_pick',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='picklist_data',
            name='third_pick',
            field=models.JSONField(default=list),
        ),
    ]
