# Generated by Django 5.1.4 on 2026-01-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_color', models.CharField(default='#e74c3c', max_length=7)),
                ('logo_url', models.CharField(default='/static/images/EagleForceLogo.png', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
