# Generated by Django 5.1.4 on 2025-09-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizeduser',
            name='is_admin',
        ),
    ]
